### PR TITLE
Run rspec

### LINKED ISSUE #175: Fails to authenticate with the same digest mechanism as Savon 2.1.1
This test is failing:
```
      # correct digest auth
      lambda { savon(:check_auth, 42){ wsse_auth "gorilla", "secret", :digest } }.
        should_not raise_exception(Savon::SOAPFault)
```

Stepping through it, when savon is invoked it relies on Akami - and wsse_timestamp is ignored by Savon.

```
    81:     def akami
    82:       wsse = Akami.wsse
    83:       wsse.credentials(*wsse_auth) if wsse_auth
    84:       wsse.timestamp = wsse_timestamp if wsse_timestamp
    85:       if wsse_signature && wsse_signature.have_document?
    86:         wsse.signature = wsse_signature
    87:       end
    88: require 'pry'
 => 89: binding.pry
    90:       wsse
    91:     end

[1] pry(#<Savon::Header>)> wsse
=> #<Akami::WSSE:0x007f07dbeaa940 @digest=:digest, @password="secret", @username="gorilla">
[2] pry(#<Savon::Header>)> wsse_timestamp
=> nil
[3] pry(#<Savon::Header>)> wsse.to_xml
=> "<wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><wsse:UsernameToken wsu:Id=\"UsernameToken-1\" xmlns:wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\"><wsse:Username>gorilla</wsse:Username><wsse:Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">MWRhYTg4NTMyMmZiNDBjMjZiOWY5ODkyNjdiMTVjMzk3MDFkMDQxYw==</wsse:Nonce><wsu:Created>2015-04-12T06:31:29Z</wsu:Created><wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">bT43FqNpm/4H2e4VD5frl3Za1Fs=</wsse:Password></wsse:UsernameToken></wsse:Security>"
```

but what we calculate is wrong
```
From: /home/clockwerx/htw-all/wash_out/lib/wash_out/wsse.rb @ line 72 WashOut::Wsse#matches_expected_digest?:

    67:       # Java
    68:       token = Base64.decode64(nonce) + timestamp.to_s + expected_password
    69:       flavors << Base64.encode64(Digest::SHA1.digest(token)).chomp!
    70: 
    71: require 'pry'
 => 72: binding.pry
    73: 
    74:       flavors.each do |f|
    75:         return true if f == password
    76:       end
    77: 

[1] pry(#<WashOut::Wsse>)> flavors
=> ["ZTdhOGMyYzhlMmJmODlmNTMzYWQzODgyNzYxNWJlMDY2NWE0OTcwYQ==", "lqkg7jFUklTntMDjILxfR8Ehb9U="]
[2] pry(#<WashOut::Wsse>)> timestamp
=> Sun, 12 Apr 2015 06:31:29 +0000
[3] pry(#<WashOut::Wsse>)> nonce
=> "ZDE4YzY2ZDYxZTkxOTE3ZmQwODdmNTljODkzMzZmMWZmZDQxZWFmZQ=="
[4] pry(#<WashOut::Wsse>)> offset_in_minutes
=> 0
[5] pry(#<WashOut::Wsse>)> expected_password
=> "secret"
[6] pry(#<WashOut::Wsse>)> timestamp.to_s
=> "2015-04-12T06:31:29+00:00"
[7] pry(#<WashOut::Wsse>)> timestamp.to_s
=> "2015-04-12T06:31:29+00:00"
[8] pry(#<WashOut::Wsse>)> nonce
=> "ZDE4YzY2ZDYxZTkxOTE3ZmQwODdmNTljODkzMzZmMWZmZDQxZWFmZQ=="
[9] pry(#<WashOut::Wsse>)> nonce + timestamp.to_s + expected_password
=> "ZDE4YzY2ZDYxZTkxOTE3ZmQwODdmNTljODkzMzZmMWZmZDQxZWFmZQ==2015-04-12T06:31:29+00:00secret"
[10] pry(#<WashOut::Wsse>)> token
=> "d18c66d61e91917fd087f59c89336f1ffd41eafe2015-04-12T06:31:29+00:00secret"
[11] pry(#<WashOut::Wsse>)> Digest::SHA1.hexdigest(token)
=> "96a920ee31549254e7b4c0e320bc5f47c1216fd5"
[12] pry(#<WashOut::Wsse>)> Base64.encode64(Digest::SHA1.hexdigest(token))
=> "OTZhOTIwZWUzMTU0OTI1NGU3YjRjMGUzMjBiYzVmNDdjMTIxNmZkNQ==\n"
[13] pry(#<WashOut::Wsse>)> Base64.encode64(Digest::SHA1.hexdigest(token)).chomp!
=> "OTZhOTIwZWUzMTU0OTI1NGU3YjRjMGUzMjBiYzVmNDdjMTIxNmZkNQ=="
[14] pry(#<WashOut::Wsse>)> password
=> "+eA+Z8NVFFUNABO5DWNgR6MDKNA="
```
I suspect this is because of an input timestamp of 
```
2015-04-12T06:31:29Z
```
vs

```
timestamp.to_s # 2015-04-12T06:31:29+00:00
```

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Travis isn't actually running any specs; just bundling.

https://travis-ci.org/inossidabile/wash_out/jobs/50445620

Additionally:
 * Fixes #175 with explicit behaviour
 * Fixes a large variety of modern rspec deprecations

### CODE REVIEW

File: lib/wash_out/wsse.rb [hunk 1]
```diff
@@ -62,11 +61,11 @@ def matches_expected_digest?(password)
       flavors = Array.new
 
       # Ruby / Savon
-      token = nonce + timestamp.to_s + expected_password
+      token = nonce + timestamp.strftime("%Y-%m-%dT%H:%M:%SZ") + expected_password
```
Comment (CloCkWeRX) [inline lib/wash_out/wsse.rb]: Here I've assumed that a WSSE WSU createdAt will always be an xs:dateTime expressed in the canconcial way ( http://www.w3.org/TR/xmlschema-2/#dateTime - "The mapping so defined is one-to-one, except that '+00:00', '-00:00', and 'Z' all represent the same zero-length duration timezone, UTC; 'Z' is its canonical representation.")

File: lib/wash_out/wsse.rb [hunk 2]
```diff
@@ -62,11 +61,11 @@ def matches_expected_digest?(password)
...
       flavors << Base64.encode64(Digest::SHA1.hexdigest(token)).chomp!
 
       # Java
-      token = Base64.decode64(nonce) + timestamp.to_s + expected_password
+      token = Base64.decode64(nonce) + timestamp.strftime("%Y-%m-%dT%H:%M:%SZ") + expected_password
```
Comment (CloCkWeRX) [inline lib/wash_out/wsse.rb]: anddddd there's no explicit test coverage of this one, I've just assumed that it'll have the same bug.
